baseURL = "https://dbb.tw"
title = "天天放空"
theme = "PaperMod"

languageCode = "zh-tw"
defaultContentLanguage = "zh-tw"
hasCJKLanguage = true
enableRobotsTXT = true
googleAnalytics = "G-9S0DRXDL6T"

[params]
  ShowPostNavLinks = true
  images = ["/og-default.jpg"]

[params.footer]
  copyright = "© 2025 天天放空 — All rights reserved."
  poweredby = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 10

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 20

[[menu.main]]
  name = "Archive"
  url = "/archives/"
  weight = 30

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 40
